### ISSUE TITLE
Feature Request: import/export Characters from CharacterSheet

### ISSUE THREAD

**Issue by osfrance** [Rolisteam/RCharacterSheet#7]
It's possible to include function to import/export in json file Characters from CharacterSheet .RCS file ?

I think, it's be nice to dissossiate characters from charactersheets, because if for example : 
I have one charactersheet from one game session whit player 1, 
and another charactersheet with same fields (from another game session) with player 2 
and I want to include player2 from game session 2 to RCS from game session 1 ...

Import/export to json File is great if GM want to make a NoSQL database (like MongoDb) to store players characters !

Thanks for you opinion

**Comment by obiwankennedy** [comment]
The rcs file is a json file, so you just have to copy/paste the array of characters if you want to extract the data.

**Comment by osfrance** [comment]
Yes, i see that, but the RCS file is a little big from an text editor, it's hard to edit file (I think is because the image bin is stored on file)

**Comment by obiwankennedy** [comment]
https://invent.kde.org/kde/rolisteam-community-data/-/blob/master/scripts/convertSheet.py 

I did not finish to test it but the export work fine.

> ./convertSheet.py -i path/to/sheet.rcs -e character.json

In character.json all data about character are stored.

If you can use kde gitlab for issues is better. I try to let github be a secondary place now. 

Please put your next ticket here:
https://invent.kde.org/kde/rolisteam
https://invent.kde.org/kde/rolisteam-diceparser
https://invent.kde.org/kde/rcse
https://invent.kde.org/kde/rcharactersheet

**Comment by osfrance** [comment]
Oh thanks a lot !!!! Ok If I understand : I put issue on Github and Feature request on Kde (gitlab) ?

**Comment by obiwankennedy** [comment]
No, put every thing on gitlab of kde and stop using github.

**Comment by osfrance** [comment]
Ok !
